// MY-OWN-CHEF-BOOK-API
export interface recipesDataSet {
    id: number;
    title: string;
    category: string[];
    // ingredients: string[];
    // preparation: string;
    state: boolean;
    // prepTime: number;
    // cookTime: number;// Generated by https://quicktype.io
}

export interface RecipeResponse {
  ok: boolean;
  recetas: Receta[];
}

export interface Receta {
  id:              number;
  title:           string;
  preparation:     string;
  category:        string;
  tags:            string;
  isFromTheMealDB: boolean;
  state:           boolean;
  createdAt:       string;
  updatedAt:       string;
}

  